# NebulaGraph Configuration (Default Fallback)
nebula.hosts=127.0.0.1:9669
nebula.username=root
nebula.password=nebula
nebula.space=test
nebula.connection_pool_size=10
nebula.timeout=60000
graph.storage.type=nebula

# Milvus Configuration (Default Fallback)
milvus.uri=http://127.0.0.1:19530
milvus.username=root
milvus.password=
milvus.collection=node_vectors
milvus.dimension=1024
graph.vector.enabled=true

# OpenAI Configuration
embedding.url=https://api.siliconflow.cn/v1/embeddings
embedding.model=BAAI/bge-m3
embedding.api_key=sk-sttkzgppyhkmcgbuasbvxbkddqavqthpictybjmmewfalbfv


# global library configuration
global.library_path=./library
global.decompile_output_path=./library/output
project.discard.regx.list=.*GeneratedCriteria.*


# Project Configuration
project.root_path=E:\\MercurjiangWorkSpace\\Projects\\WeBlog-master
project.id=demo
project.branch=master